baseURL = "http://shamalscreations.in"
languageCode = "en-us"
title = "Shamal's Creations"
theme = "hugo-shopping-product-catalogue-simple"

[params]
    subtitle = "Contact: Shamal Joshi (+91 98812 32634)"
    aboutus="Contact: Shamal Joshi (+91 98812 32634)"
